### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by RichardLitt** [colinbatchelor/gdbank#1]
Hey @colinbatchelor - is this repository only for your own resources, or are you planning to build it into a place linking to other resources, as well? Curious. What are your goals for this repository? 

Thanks!

**Comment by colinbatchelor** [comment]
Hello,

You're right - I do need to link to at the very least other Scottish Gaelic resources, for example ARCOSG, and Teresa Lynn's work on Irish. This is coming!

Best wishes,
Colin.

**Comment by RichardLitt** [comment]
No worries. I've started a list, here: https://github.com/RichardLitt/gaelic-resources, to complement https://github.com/RichardLitt/endangered-languages. Maybe we can work together on it?
